// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SynopsisV2.Infrastructure.Persistence;

#nullable disable

namespace SynopsisV2.Infrastructure.Infrastructure.Persistence
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgendaSpeaker", b =>
                {
                    b.Property<Guid>("AgendasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SpeakersId")
                        .HasColumnType("int");

                    b.HasKey("AgendasId", "SpeakersId");

                    b.HasIndex("SpeakersId");

                    b.ToTable("AgendaSpeaker");
                });

            modelBuilder.Entity("Synopsis.Infrastructure.DbContext.Entities.Error", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime")
                        .HasColumnOrder(1);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("Synopsis.Infrastructure.DbContext.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Important")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int?>("IsShow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<int?>("SynopsisType")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<int?>("Type")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("URL")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("SynopsisV2.Domain.Entities.Agenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SynopsisType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicRu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("SynopsisV2.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateTimeSend")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("SynopsisV2.Domain.Entities.Logo", b =>
                {
                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SpeakerId")
                        .HasColumnType("int");

                    b.HasKey("LogoPath", "SpeakerId");

                    b.HasIndex("SpeakerId", "LogoPath")
                        .IsUnique();

                    b.ToTable("Logos");
                });

            modelBuilder.Entity("SynopsisV2.Domain.Entities.Site", b =>
                {
                    b.Property<int>("SpeakerId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyNameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyNameRu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeakerId", "Link");

                    b.HasIndex("SpeakerId", "Link")
                        .IsUnique();

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("SynopsisV2.Domain.Entities.Speaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BiographyEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BiographyRu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Important")
                        .HasColumnType("int")
                        .HasColumnOrder(8);

                    b.Property<int?>("IsCommission")
                        .HasColumnType("int")
                        .HasColumnOrder(10);

                    b.Property<int?>("IsFavorite")
                        .HasColumnType("int")
                        .HasColumnOrder(11);

                    b.Property<int?>("IsShow")
                        .HasColumnType("int")
                        .HasColumnOrder(9);

                    b.Property<string>("Linkedin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medium")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<string>("NameRu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int")
                        .HasColumnName("PartnerId")
                        .HasColumnOrder(12);

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<string>("PositionEn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<string>("PositionRu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<int?>("SynopsisType")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.HasKey("Id")
                        .HasName("PK__Speakers__02899F87A657070E");

                    b.HasIndex("PartnerId");

                    b.ToTable("Speakers");
                });

            modelBuilder.Entity("SynopsisV2.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(6);

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(7);

                    b.Property<string>("Telegram")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<int?>("Type")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<string>("WalletBsc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WalletBSC")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("AgendaSpeaker", b =>
                {
                    b.HasOne("SynopsisV2.Domain.Entities.Agenda", null)
                        .WithMany()
                        .HasForeignKey("AgendasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SynopsisV2.Domain.Entities.Speaker", null)
                        .WithMany()
                        .HasForeignKey("SpeakersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SynopsisV2.Domain.Entities.Logo", b =>
                {
                    b.HasOne("SynopsisV2.Domain.Entities.Speaker", "Speaker")
                        .WithMany("Logos")
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("SynopsisV2.Domain.Entities.Site", b =>
                {
                    b.HasOne("SynopsisV2.Domain.Entities.Speaker", "Speaker")
                        .WithMany("Sites")
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("SynopsisV2.Domain.Entities.Speaker", b =>
                {
                    b.HasOne("Synopsis.Infrastructure.DbContext.Entities.Partner", "Partner")
                        .WithMany("Speakers")
                        .HasForeignKey("PartnerId");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Synopsis.Infrastructure.DbContext.Entities.Partner", b =>
                {
                    b.Navigation("Speakers");
                });

            modelBuilder.Entity("SynopsisV2.Domain.Entities.Speaker", b =>
                {
                    b.Navigation("Logos");

                    b.Navigation("Sites");
                });
#pragma warning restore 612, 618
        }
    }
}
